language: node_js
node_js:
  - "node"
before_script:
  - npm run setup
  - npm run test
script:
  - npm run build
after_success:
  - git config --local user.name "travis"
  - git config --local user.email "github@realeyes.com"
  - export VERSION=`npm version $(echo $VERSION_BUMP_TYPE)`
  - git add -A
  - git commit -m 'Version bump'
  - git tag $VERSION
  - git push origin master && git push --tags
  - npm pack
deploy:
  provider: npm
  email: shared-by-developers@realeyes.com
  api_key:
    secure: $NPM_API_TOKEN
  on:
    tags: true
    repo: realeyes-media/mp4pssh
