language: node_js
node_js:
  - "node"
before_script:
  - npm run setup
  - npm run test
script:
  - npm run build
before_deploy:
  - git config --global user.email github@realeyes.com
  - git config --global user.name "Travis"
  - git add -A
  - git commit -m 'Update package lock'
  - npm version $VERSION_BUMP_TYPE -m "Bumping to %s"
  - git push origin master --tags
  - npm pack
deploy:
  provider: npm
  email: shared-by-developers@realeyes.com
  api_key:
    secure: $NPM_API_TOKEN
  on:
    branch: master
    repo: realeyes-media/mp4pssh
