language: node_js
node_js:
  - "node"
before_script:
  - npm run setup
  - npm run test
script:
  - npm run build
before_deploy:
  # - git config --global user.email github@realeyes.com
  # - git config --global user.name "Travis"
  # - git config --global credential.helper 'store --file .git/credentials'
  # - echo "https://${GITHUB_API_KEY}:@github.com" > .git/credentials
  # - git add -A
  # - git commit -m 'Update package lock [skip ci]'
  # - npm version $VERSION_BUMP_TYPE -m "Bumping to %s"
  # - git push origin HEAD:master --tags
deploy:
  provider: npm
  email: matthew@realeyes.com
  api_key:
    secure: $NPM_API_TOKEN
  on:
    branch: master
