language: node_js
node_js:
  - "node"
before_script:
  - npm run setup
  - npm run build
script:
  - npm run test
after_success:
  - npm pack
deploy:
  provider: npm
  tag: next
  email: shared-by-developers@realeyes.com
  api_key:
    secure: hI+FOUJjcoSXkzmljf6AUz3kGc6N85BhEX7zfB2qrRkVt8/LBiQSYC+BThzdl1Z1t0GMnwElva2ZPxrkhwNi/dINJoYiJdWeqvb8TYcagaXZcsx3zyhadQZGD1VUXtCwXK2exJV+RwvfY9Yi0uhVHmQ4iP7wtQjWNyxbtgSSMzJzRRB3RVlC6DGTVd5hIKqjyjwqHgtSeIz4BhzjxTD0AtLxoEiX5G09ulZ2nG/g4DiMvpykKs8LmlIfwY3Wqf/eGLHiDqB8faa6XULxfklk/ZZLV6KVY9sdJbBeC9F8miiLiQXV8SFVYZJjoqHUSmPxRSdn85r4jed0YbrlmAn1VgU3YY7srgi/ko8o/RmYsy8OnZWzodfcs+7QAvdKqbcOhJ0jP3HtnAoXMbXw5/YptsYLeSRvCnDXegBSVgv2M0kY1F06osIFeUeBTOaSeGpq7R9/mqdj22nft95HWfxnSdSeW3gmRqP+3oBx7feuXIil1gsTIU8uxs/KF+APPosaGB/N3YvzwSxLltuv+YdouQmRpp2+nDcwE4pYUtVaP5eFDQrlSs7nY9m72hHo1CyCCp9Rt5uiU4MNpjDtYONHkanqI6mltMGjY+lo8MpVbv35gtucbOQLa1qAiROiZWvTZusree9uNrE48OTSxOZ4WdD+LS44GO1UF0tv7z9cXQc=
  on:
    tags: true
    repo: realeyes-media/mp4pssh
